# Generated by Django 5.0.1 on 2024-12-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trabajador',
        ),
    ]
